version: '3.4'

services:
  myapp-frontend:
    image: job-aplication-form
    build:
      context: C:\FormApp\job-application-form
      dockerfile: Dockerfile
    # Frontend, Nginx üzerinden erişilecek, bu yüzden dışa açık port tanımını kaldırıyoruz.

  myapp-backend:
    image: hrwebapi
    build:
      context: C:\FormApp\HrWebAPI-main
      dockerfile: Dockerfile
    # Backend, Nginx üzerinden erişilecek, bu yüzden dışa açık port tanımını kaldırıyoruz.

  nginx:
    image: nginx
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - myapp-frontend
      - myapp-backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    depends_on:
      - nginx
